# Generated by Django 3.1.7 on 2021-06-09 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=9)),
                ('description', models.TextField(blank=True)),
                ('accommodation_type', models.CharField(choices=[('R', 'Room'), ('H', 'House')], max_length=1)),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('available', models.BooleanField(default=True)),
                ('publish_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
    ]
