# Generated by Django 3.1.7 on 2021-06-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('lift', models.BooleanField()),
                ('accessibility', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('heater', models.BooleanField()),
                ('outside_area', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('tv', models.BooleanField()),
                ('energy_certificate', models.CharField(blank=True, max_length=2)),
                ('smoking', models.BooleanField()),
                ('guest_stay', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('furnished', models.BooleanField(default=False)),
                ('solar_orientation', models.CharField(choices=[('N', 'North'), ('NE', 'Northeast'), ('NW', 'Northwest'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('E', 'East'), ('W', 'West')], max_length=2)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation')),
            ],
        ),
    ]
