# Generated by Django 3.1.7 on 2021-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('landlord_iban', models.CharField(blank=True, max_length=34)),
                ('amount', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('date_effected', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
