# Generated by Django 3.1.7 on 2021-06-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly'), ('S', 'Semiannual')], max_length=1)),
                ('price_per_month', models.IntegerField()),
                ('mininum_stay', models.IntegerField()),
                ('expenses', models.BooleanField()),
                ('cleaning_service', models.BooleanField()),
                ('refund_policy', models.TextField(blank=True)),
                ('safety_deposit', models.IntegerField()),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation')),
            ],
        ),
    ]
